node:
  port: 8080
  dir: ".node"
  peers: "peers.json"
  control:
    - protocol: "ws"
      port: 7071
    - protocol: "http"
      port: 7072
chain:
  database: "chain"
  genesis:
    value: 50.0
holder:
  privateKey: "holder.ecdsa"
