holder:
  privateKey: "holder.ecdsa"
node:
  port: 8080
  dir: ".node"
  control:
    - protocol: "ws"
      port: 7071
    - protocol: "http"
      port: 7072
  discover:
    listeningPort: 8081
    bootnodes:
      - addr: "127.0.0.1"
        port: 8082
    useStun: false
    stunAddr: ""
chain:
  database: "chain"
  genesis:
    value: 50.0
